# Generated by Django 4.0.1 on 2022-01-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locomotiv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locomotiv_name', models.CharField(max_length=32)),
                ('locomotiv_seria', models.CharField(max_length=32)),
                ('locomotiv_number', models.CharField(max_length=32)),
                ('type_locomotiv', models.IntegerField(choices=[(1, 'Manyovr Lokomotivi'), (2, 'Poyezd Lokomotivi')])),
                ('value_ao', models.DecimalField(decimal_places=5, max_digits=10)),
                ('value_bo', models.DecimalField(decimal_places=5, max_digits=10)),
                ('value_co', models.DecimalField(decimal_places=5, max_digits=10)),
                ('value_aox', models.DecimalField(decimal_places=5, max_digits=10)),
                ('value_box', models.DecimalField(decimal_places=5, max_digits=10)),
                ('value_cox', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
            options={
                'verbose_name': 'Lokomotiv Turi',
                'verbose_name_plural': 'Lokomotiv Turlari',
            },
        ),
    ]
