# Generated by Django 4.0.1 on 2022-02-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locomotiv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locomotiv',
            name='locomotiv_name',
            field=models.CharField(max_length=32, verbose_name='Lokomotiv nomi'),
        ),
        migrations.AlterField(
            model_name='locomotiv',
            name='locomotiv_number',
            field=models.CharField(max_length=32, verbose_name='Lokomotiv raqami'),
        ),
        migrations.AlterField(
            model_name='locomotiv',
            name='locomotiv_seria',
            field=models.CharField(max_length=32, verbose_name='Lokomotiv seriyasi'),
        ),
        migrations.AlterField(
            model_name='locomotiv',
            name='type_locomotiv',
            field=models.IntegerField(choices=[(1, 'Manyovr Lokomotivi'), (2, 'Poyezd Lokomotivi')], verbose_name='Lokomotiv turi'),
        ),
        migrations.AlterField(
            model_name='locomotiv',
            name='value_ao',
            field=models.DecimalField(decimal_places=5, max_digits=10, verbose_name='ao qiymati'),
        ),
        migrations.AlterField(
            model_name='locomotiv',
            name='value_aox',
            field=models.DecimalField(decimal_places=5, max_digits=10, verbose_name='aox qiymati'),
        ),
        migrations.AlterField(
            model_name='locomotiv',
            name='value_bo',
            field=models.DecimalField(decimal_places=5, max_digits=10, verbose_name='bo qiymati'),
        ),
        migrations.AlterField(
            model_name='locomotiv',
            name='value_box',
            field=models.DecimalField(decimal_places=5, max_digits=10, verbose_name='box qiymati'),
        ),
        migrations.AlterField(
            model_name='locomotiv',
            name='value_co',
            field=models.DecimalField(decimal_places=5, max_digits=10, verbose_name='co qiymati'),
        ),
        migrations.AlterField(
            model_name='locomotiv',
            name='value_cox',
            field=models.DecimalField(decimal_places=5, max_digits=10, verbose_name='cox qiymati'),
        ),
    ]
