# Generated by Django 4.0.1 on 2022-02-09 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locomotiv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainResistanceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField()),
                ('locomotiv_traction_mode', models.FloatField()),
                ('locomotiv_idle_mode', models.FloatField()),
                ('total_resistance_vagon', models.FloatField()),
                ('total_resistance_traction', models.FloatField()),
                ('total_resistance_idle', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Excel',
        ),
    ]
