# Generated by Django 4.0.1 on 2022-02-03 16:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('locomotiv', '0002_alter_locomotiv_locomotiv_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locomotiv',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 2, 3, 16, 32, 53, 858753, tzinfo=utc), verbose_name='Yaratilgan vaqt'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locomotiv',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AddField(
            model_name='locomotiv',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Tahrirlangan vaqt'),
        ),
    ]
