# Generated by Django 4.0.1 on 2022-03-01 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locomotiv', '0003_totaldatavagon_load_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='RailwaySwitchMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Nomi')),
                ('mark', models.CharField(max_length=16, verbose_name='Markasi')),
                ('a', models.FloatField(verbose_name='a masofasi uzunligi')),
                ('b', models.FloatField(verbose_name='b masofasi uzunligi')),
                ('rail_type', models.CharField(blank=True, max_length=16, null=True, verbose_name='Rels turi')),
            ],
            options={
                'verbose_name': "Stelkali o'tkazgich markasi",
                'verbose_name_plural': "Strelkali o'tkazgichlar markalari",
            },
        ),
        migrations.AddField(
            model_name='locomotiv',
            name='lenght',
            field=models.FloatField(default=20, verbose_name='Lokomotiv uzunligi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locomotiv',
            name='number_arrows',
            field=models.SmallIntegerField(default=8, verbose_name="O'qlar soni"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locomotiv',
            name='weigth',
            field=models.FloatField(default=120, verbose_name="Lokomotiv og'irligi"),
            preserve_default=False,
        ),
    ]
