# Generated by Django 4.0.1 on 2022-02-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locomotiv', '0003_locomotiv_created_at_locomotiv_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalDataVagon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_vagon', models.IntegerField(verbose_name='Vagon raqami')),
                ('number_of_arrow', models.SmallIntegerField(verbose_name="O'qlar soni")),
                ('netto_vagon', models.DecimalField(decimal_places=3, max_digits=6, verbose_name="Vagon og'irligi")),
                ('length_vagon', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Vagon uzunligi')),
                ('total_weight', models.DecimalField(decimal_places=3, max_digits=6, verbose_name="Umumiy og'irlik")),
                ('bullet_weight', models.DecimalField(decimal_places=20, max_digits=50, verbose_name="O'qqa tushadigan og'irlik")),
            ],
            options={
                'verbose_name': 'Vagon xarakteristikasi',
                'verbose_name_plural': 'Vagonlar xarakteristikasi',
            },
        ),
    ]
