# Generated by Django 4.0.1 on 2022-02-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locomotiv', '0004_totaldatavagon'),
    ]

    operations = [
        migrations.CreateModel(
            name='VagonResistanceConstant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_ao', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='ao qiymati')),
                ('value_bo', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='bo qiymati')),
                ('value_co', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='co qiymati')),
                ('value_aox', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='aox qiymati')),
                ('value_box', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='box qiymati')),
                ('value_cox', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='cox qiymati')),
            ],
            options={
                'verbose_name': "Vagon Qarshili uchun o'zgarmas qiymat",
                'verbose_name_plural': "Vagon Qarshili uchun o'zgarmas qiymatlar",
            },
        ),
    ]
