# Generated by Django 4.0.1 on 2022-03-01 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locomotiv', '0004_locomotiv_lenght_locomotiv_number_arrows_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RailwaySwitchMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Nomi')),
                ('mark', models.CharField(max_length=16, verbose_name='Markasi')),
                ('a', models.FloatField(verbose_name='a masofasi uzunligi')),
                ('b', models.FloatField(verbose_name='b masofasi uzunligi')),
                ('rail_type', models.CharField(blank=True, max_length=16, null=True, verbose_name='Rels turi')),
            ],
            options={
                'verbose_name': "Stelkali o'tkazgich markasi",
                'verbose_name_plural': "Strelkali o'tkazgichlar markalari",
            },
        ),
    ]
