# Generated by Django 4.0.1 on 2022-02-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locomotiv', '0005_vagonresistanceconstant'),
    ]

    operations = [
        migrations.AddField(
            model_name='vagonresistanceconstant',
            name='value_ax',
            field=models.DecimalField(decimal_places=5, default=1.1, max_digits=10, verbose_name='ax qiymati'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vagonresistanceconstant',
            name='value_cx',
            field=models.DecimalField(decimal_places=5, default=1.1, max_digits=10, verbose_name='cx qiymati'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vagonresistanceconstant',
            name='value_box',
            field=models.DecimalField(decimal_places=5, max_digits=10, verbose_name='bx qiymati'),
        ),
    ]
