# Generated by Django 4.0.1 on 2022-03-01 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locomotiv', '0005_railwayswitchmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='railwayswitchmark',
            name='length_curvature',
            field=models.IntegerField(default=300, verbose_name='Egrilik uzunligi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='railwayswitchmark',
            name='radius',
            field=models.IntegerField(default=300, verbose_name='Egrilik radiusi'),
            preserve_default=False,
        ),
    ]
