# Generated by Django 4.0.1 on 2022-03-01 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locomotiv', '0006_railwayswitchmark_length_curvature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='railwayswitchmark',
            name='title',
            field=models.CharField(blank=True, max_length=128, verbose_name='Nomi'),
        ),
    ]
