# Generated by Django 4.0.1 on 2022-02-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locomotiv', '0006_vagonresistanceconstant_value_ax_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vagonresistanceconstant',
            name='value_box',
        ),
        migrations.AddField(
            model_name='vagonresistanceconstant',
            name='value_bx',
            field=models.FloatField(default=1.1, verbose_name='bx qiymati'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='locomotiv',
            name='is_active',
            field=models.FloatField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='locomotiv',
            name='value_ao',
            field=models.FloatField(verbose_name='ao qiymati'),
        ),
        migrations.AlterField(
            model_name='locomotiv',
            name='value_aox',
            field=models.FloatField(verbose_name='aox qiymati'),
        ),
        migrations.AlterField(
            model_name='locomotiv',
            name='value_bo',
            field=models.FloatField(verbose_name='bo qiymati'),
        ),
        migrations.AlterField(
            model_name='locomotiv',
            name='value_box',
            field=models.FloatField(verbose_name='box qiymati'),
        ),
        migrations.AlterField(
            model_name='locomotiv',
            name='value_co',
            field=models.FloatField(verbose_name='co qiymati'),
        ),
        migrations.AlterField(
            model_name='locomotiv',
            name='value_cox',
            field=models.FloatField(verbose_name='cox qiymati'),
        ),
        migrations.AlterField(
            model_name='totaldatavagon',
            name='bullet_weight',
            field=models.FloatField(verbose_name="O'qqa tushadigan og'irlik"),
        ),
        migrations.AlterField(
            model_name='totaldatavagon',
            name='length_vagon',
            field=models.FloatField(verbose_name='Vagon uzunligi'),
        ),
        migrations.AlterField(
            model_name='totaldatavagon',
            name='netto_vagon',
            field=models.FloatField(verbose_name="Vagon og'irligi"),
        ),
        migrations.AlterField(
            model_name='totaldatavagon',
            name='total_weight',
            field=models.FloatField(verbose_name="Umumiy og'irlik"),
        ),
        migrations.AlterField(
            model_name='vagonresistanceconstant',
            name='value_ao',
            field=models.FloatField(verbose_name='ao qiymati'),
        ),
        migrations.AlterField(
            model_name='vagonresistanceconstant',
            name='value_aox',
            field=models.FloatField(verbose_name='aox qiymati'),
        ),
        migrations.AlterField(
            model_name='vagonresistanceconstant',
            name='value_ax',
            field=models.FloatField(verbose_name='ax qiymati'),
        ),
        migrations.AlterField(
            model_name='vagonresistanceconstant',
            name='value_bo',
            field=models.FloatField(verbose_name='bo qiymati'),
        ),
        migrations.AlterField(
            model_name='vagonresistanceconstant',
            name='value_co',
            field=models.FloatField(verbose_name='co qiymati'),
        ),
        migrations.AlterField(
            model_name='vagonresistanceconstant',
            name='value_cox',
            field=models.FloatField(verbose_name='cox qiymati'),
        ),
        migrations.AlterField(
            model_name='vagonresistanceconstant',
            name='value_cx',
            field=models.FloatField(verbose_name='cx qiymati'),
        ),
    ]
