# Generated by Django 4.0.1 on 2022-03-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locomotiv', '0007_alter_railwayswitchmark_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='RailRoadCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('coefficient', models.FloatField()),
            ],
            options={
                'verbose_name': "Yo'l xarakteristikasi",
                'verbose_name_plural': "Yo'l xarakteristikasi",
            },
        ),
    ]
