# Generated by Django 4.0.1 on 2022-02-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locomotiv', '0007_remove_vagonresistanceconstant_value_box_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vagonresistanceconstant',
            name='value_box',
            field=models.FloatField(default=1.1, verbose_name='cox qiymati'),
            preserve_default=False,
        ),
    ]
