# Generated by Django 4.0.1 on 2022-02-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locomotiv', '0008_vagonresistanceconstant_value_box'),
    ]

    operations = [
        migrations.CreateModel(
            name='Excel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/', verbose_name='Excel file')),
            ],
            options={
                'verbose_name': 'Excel file',
                'verbose_name_plural': 'Excel filelar',
            },
        ),
    ]
