# Generated by Django 4.0.1 on 2022-03-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locomotiv', '0008_railroadcharacteristic'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainresistancedata',
            name='all_idle_resistance',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainresistancedata',
            name='all_traction_resistance',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainresistancedata',
            name='curvature_resistance',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainresistancedata',
            name='declivity_resistance',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainresistancedata',
            name='outside_temperature_resistance',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainresistancedata',
            name='railroad_condition_resistance',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainresistancedata',
            name='resistance_vagon_ahead',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainresistancedata',
            name='specific_idle_resistance',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainresistancedata',
            name='specific_traction_resistance',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainresistancedata',
            name='switch_curvature_resistance',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainresistancedata',
            name='wind_capacity_resistance',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
