# Generated by Django 4.0.1 on 2022-02-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locomotiv', '0009_excel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locomotiv',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
    ]
