# Generated by Django 4.0.1 on 2022-04-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locomotiv', '0010_locomotiv_force_all_arrows_locomotiv_force_per_arrow'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locomotiv_weight', models.FloatField()),
                ('vagons_weight', models.FloatField()),
            ],
        ),
    ]
