# Generated by Django 4.0.1 on 2022-04-21 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locomotiv', '0011_weightmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightmodel',
            name='locomotiv',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='locomotiv.locomotiv'),
            preserve_default=False,
        ),
    ]
