# Generated by Django 4.0.1 on 2024-03-12 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StationRoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('type', models.CharField(choices=[('main', 'main'), ('sorting_road', 'sorting_road')], max_length=16)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='station.station')),
            ],
        ),
        migrations.CreateModel(
            name='SortingRoadSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_point', models.CharField(max_length=255)),
                ('end_point', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('road', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='station.stationroad')),
            ],
        ),
    ]
