# Generated by Django 4.0.1 on 2024-03-12 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0002_sortingroadspecialization_single_point_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortingroadspecialization',
            name='end_point',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='sortingroadspecialization',
            name='single_point',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='sortingroadspecialization',
            name='start_point',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
