# Generated by Django 4.0.1 on 2024-03-13 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0003_alter_sortingroadspecialization_end_point_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NaturalList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vagon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_vagon', models.IntegerField(verbose_name='Vagon raqami')),
                ('vagon_type', models.CharField(choices=[('kr', 'kr'), ('pr', 'pr'), ('pl', 'pl'), ('sys', 'sys'), ('xp', 'xp'), ('pv', 'pv'), ('rf', 'rf')], max_length=8, null=True)),
                ('load_weight', models.FloatField(verbose_name="Yuk og'irligi")),
                ('number_of_arrow', models.SmallIntegerField(verbose_name="O'qlar soni")),
                ('netto_vagon', models.FloatField(verbose_name="Vagon og'irligi")),
                ('length_vagon', models.FloatField(verbose_name='Vagon uzunligi')),
                ('total_weight', models.FloatField(verbose_name="Umumiy og'irlik")),
                ('bullet_weight', models.FloatField(verbose_name="O'qqa tushadigan og'irlik")),
                ('natural_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='station.naturallist')),
            ],
        ),
    ]
