# Generated by Django 4.0.1 on 2024-03-13 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0004_naturallist_vagon'),
    ]

    operations = [
        migrations.AddField(
            model_name='vagon',
            name='destination_station',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='vagon',
            name='road_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='station.stationroad'),
        ),
        migrations.AlterField(
            model_name='sortingroadspecialization',
            name='end_point',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sortingroadspecialization',
            name='single_point',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sortingroadspecialization',
            name='start_point',
            field=models.IntegerField(null=True),
        ),
    ]
