# Generated by Django 4.0.1 on 2024-03-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0005_vagon_destination_station_vagon_road_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vagon',
            name='bullet_weight',
            field=models.FloatField(null=True, verbose_name="O'qqa tushadigan og'irlik"),
        ),
        migrations.AlterField(
            model_name='vagon',
            name='length_vagon',
            field=models.FloatField(null=True, verbose_name='Vagon uzunligi'),
        ),
        migrations.AlterField(
            model_name='vagon',
            name='load_weight',
            field=models.FloatField(null=True, verbose_name="Yuk og'irligi"),
        ),
        migrations.AlterField(
            model_name='vagon',
            name='netto_vagon',
            field=models.FloatField(null=True, verbose_name="Vagon og'irligi"),
        ),
        migrations.AlterField(
            model_name='vagon',
            name='number_of_arrow',
            field=models.SmallIntegerField(null=True, verbose_name="O'qlar soni"),
        ),
        migrations.AlterField(
            model_name='vagon',
            name='total_weight',
            field=models.FloatField(null=True, verbose_name="Umumiy og'irlik"),
        ),
    ]
