# Generated by Django 4.0.1 on 2024-03-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0006_alter_vagon_bullet_weight_alter_vagon_length_vagon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vagon',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
